### ISSUE TITLE
Report status using Workflow Commands rather than the Checks API.

### ISSUE THREAD

**Issue by CraigSiemens** [wearerequired/lint-action#118]
For security reasons, it'd be preferable to not pass a GitHub token to an action if it isn't absolutely needed. 

[Workflow commands for GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#logging-commands) allows an action to report the status back without doing an API call. It's a specific format of log messages that GitHub will automatically parse and show in the pull request.

**Comment by ocean90** [comment]
Hi, thanks for the feedback. The whole concept of this action is based on the Checks API and cannot be replaced with workflow commands for simple logging.
