### ISSUE TITLE
throw new Error(`Exiting because of unhandled promise rejection`);

### ISSUE THREAD

**Issue by shamprasadrh** [wearerequired/lint-action#126]
Getting unhandled promise rejection but runs file in local machine. 

   "eslint": "^7.2.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^4.0.0",

![image](https://user-images.githubusercontent.com/28918386/100994739-e9d1f500-357c-11eb-87ee-4d606cb1428c.png)

**Comment by ocean90** [comment]
Hi, to debug this can you set [`ACTIONS_RUNNER_DEBUG ` and `ACTIONS_STEP_DEBUG`](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging)? This should give you more details about the failing command.

**Comment by bhumika-soomani-tocca** [comment]
Facing this same issue, can someone please help

**Comment by R3gu1a** [comment]
Same problem here

**Comment by summerkiflain** [comment]
Also facing the same issue, I can provide more info if required.

**Comment by ocean90** [comment]
@summerkiflain Did you try the debug mode mentioned in https://github.com/wearerequired/lint-action/issues/126#issuecomment-737857717? Is it a public repo you can link to?

**Comment by summerkiflain** [comment]
@ocean90 yes I added both, nope, not a public repo.

**Comment by ocean90** [comment]
@summerkiflain What's the debug output?

**Comment by summerkiflain** [comment]
@ocean90 its like this:
<details>
  <summary>Click to see screenshot!</summary>
  
![Screen Shot 2021-03-02 at 10 33 12 AM](https://user-images.githubusercontent.com/6568048/109602983-f4cbff80-7b42-11eb-8c3c-58fbfbe8d506.png)
</details>

If I run `npx --no-install eslint --ext .js,.jsx  --no-color --format json -c .eslintrc.js --max-warnings 0 "."` in my local project setup, it exits fine and prints `ESLint found too many warnings (maximum: 0).`

**Comment by ocean90** [comment]
This seems to be because of the use of the --max-warnings argument. I don't think it should be used with this action.

**Comment by summerkiflain** [comment]
@ocean90 I have tried after removing `--max-warning 0`, but the result is still same, I was able to run it successfully if I change some rules to not show a warning, like `eqeqeq: 0, radix: 0,` in `.eslintrc.js`, but as soon as output of of eslint is bigger it fails, I think `--format json` could be the reason, can I override this?

**Comment by ocean90** [comment]
The JSON format is required otherwise the output can't be parsed, see https://github.com/wearerequired/lint-action/blob/0ecfb81538b1a97c029230fb512a8c64a5eb2988/src/linters/eslint.js#L57-L75

The size of the output could be an issue although it should show a different error message, see #96. Do you have a screenshot without `--max-warning` too?

**Comment by summerkiflain** [comment]
@ocean90 yeah I checked that later, https://github.com/wearerequired/lint-action/issues/96 is exactly the problem, is there a way we can lint only changed files for now, that would be better than a failing linter.

**Comment by ocean90** [comment]
@summerkiflain No, that's not yet possible. #47 for the tracking issue for that.
