### ISSUE TITLE
Support Running Linter Command Multiple Times

### ISSUE THREAD

**Issue by vpillinger** [wearerequired/lint-action#138]
The linter command will try to checkout the branch each time it is run, which causes the following crash:
```Adding auth information to Git remote URL
Fetching remote branch "***"
From ***
 * branch            *** -> FETCH_HEAD
Switching to the "**" branch
fatal: Cannot force update the current branch.
Error: Error: Command failed: git branch --force *** --track origin/***
fatal: Cannot force update the current branch.

/home/runner/work/_actions/wearerequired/lint-action/v1/dist/index.js:1108
	throw new Error(`Exiting because of unhandled promise rejection`);
	^

Error: Exiting because of unhandled promise rejection
    at process.<anonymous> (/home/runner/work/_actions/wearerequired/lint-action/v1/dist/index.js:1108:8)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)```
```

However, this means that I cannot run the command multiple times per action.

I would like to do this because I have a mono-repo setup where each sub-folder has its own linting config that must be run. This means that I have to maintain 3-4 different files for linting instead of relying on one file to run the various linters.

**Comment by felipedaraujo** [comment]
@vpillinger, were you able to find a solution for this issue? I am also wanting to run `wearerequired/lint-action` twice:
1st - Prettier with auto_fix targeting specific files.
2nd - ESlint, Prettier, Stylint without auto_fix targeting the whole codebase.
