### ISSUE TITLE
Enabled TwigCS on project

### ISSUE THREAD

**Issue by Ciloe** [wearerequired/lint-action#161]
Hi there ! I would like to finish this PR https://github.com/friendsoftwig/twigcs/pull/153 and maybe add the TwigCS Linter in your available linters. I would like to know how must be the output and the option I must add ?

Thanks a lot !

**Comment by ocean90** [comment]
Hi @Ciloe, the actions works best if the output is a JSON format. See for example the ESLint linter where the [command is run here](https://github.com/wearerequired/lint-action/blob/a0dac94b6d393fc9aa0b6a5abd43c1479443c2bb/src/linters/eslint.js#L35-L55) and the [output parsed here](https://github.com/wearerequired/lint-action/blob/a0dac94b6d393fc9aa0b6a5abd43c1479443c2bb/src/linters/eslint.js#L57-L104).
