### ISSUE TITLE
Linter formats package-lock.json as well

### ISSUE THREAD

**Issue by nopeless** [wearerequired/lint-action#165]
It seems that it's committing every file change after running eslint . --fix which doesn't actually affect package-lock.json, but affects the package-lock.json

**Comment by nopeless** [comment]
I found a temporary fix
```yaml
      - name: remove whatever was modifed
        run: git reset --hard && git clean -fd
```
add this before the lint action

**Comment by ocean90** [comment]
Hey there, thanks for the report. This sounds like you're not using [npm ci](https://docs.npmjs.com/cli/v7/commands/npm-ci) which wouldn't change `package-lock.json` or any other file. Can you confirm that?

**Comment by nopeless** [comment]
yes I just used `npm install`
However, I just realized that I never thought about using it in the first place
[the read me](https://github.com/wearerequired/lint-action#javascript-example-eslint-and-prettier) uses npm install instead of npm ci
but thanks for replying @ocean90

**Comment by ocean90** [comment]
The readme has been updated in #169.
