### ISSUE TITLE
Add setting to conclude check with "neutral" instead of "success" when warnings are present

### ISSUE THREAD

**Issue by inket** [wearerequired/lint-action#188]
Hi there. First of all, thanks for this awesome project! It really cut down the amount of work necessary to achieve linting through GitHub Actions.

This is a feature request/suggestion with a following pull request if you approve of such addition.

Basically, when linters finish with only warning annotations as a result, the GitHub "Check" will have the conclusion attribute set to `success`. This causes GitHub to collapse the checks section (since all the checks are green checkmarks) and might cause developers to miss that the linter actually found some warnings!

As you can see, the checks section here is collapsed
⬇️ 
<img width="918" alt="Screen Shot 2021-04-02 at 2 36 45 PM" src="https://user-images.githubusercontent.com/679224/113384390-e5013e80-93c0-11eb-9788-8ff3c8065835.png">

But upon expanding it, our linter actually found a couple of warnings! Some people might easily miss these annotations.
⬇️ 
<img width="915" alt="Screen Shot 2021-04-02 at 2 36 52 PM" src="https://user-images.githubusercontent.com/679224/113384403-eb8fb600-93c0-11eb-801c-ea510552762e.png">

My suggestion to this is to add a setting to mark such cases as `neutral` instead.
⬇️ 
<img width="918" alt="Screen Shot 2021-04-02 at 2 18 13 PM" src="https://user-images.githubusercontent.com/679224/113383324-a7031b00-93be-11eb-8446-4c043233a0be.png">

`neutral` is also the only status that doesn't look like a success/failure. (`success` would encourage developers to ignore it; `failure` would be too strict and should be reserved to actual errors)
⬇️ 
![](https://docs.github.com/assets/images/check_suites.png)

Would you be interested in adding such a feature? I'm already running [a fork](https://github.com/wearerequired/lint-action/compare/master...inket:master) that changes the logic directly and it's working fine for SwiftLint. An actual pull request would have this as a setting instead of hardcoded of course.

Thanks.

**Comment by ocean90** [comment]
Hey there, thanks for detailed issue! I think this is a great idea, please feel free to submit a PR.
