### ISSUE TITLE
Error using PAT_TOKEN which fails to create annotations

### ISSUE THREAD

**Issue by jackton1** [wearerequired/lint-action#194]
Based on the error below 

![Screen Shot 2021-04-16 at 3 28 03 PM](https://user-images.githubusercontent.com/17484350/115075233-c626a000-9ec8-11eb-9c3e-7d2c449afa9f.png)

Workflow

![Screen Shot 2021-04-16 at 3 28 41 PM](https://user-images.githubusercontent.com/17484350/115075500-287fa080-9ec9-11eb-9f26-beadf81a78d4.png)

a possible resolution here would be to use a separate token for pushing fixed changes back to the repo to prevent skipping the expected workflows which are only triggered using PAT_TOKEN's

See: https://github.com/cirrus-actions/rebase#installation

**Comment by ocean90** [comment]
Hey, I'm not sure I understand the issue. To me it sounds like your current token doesn't have the correct scopes. Why do you need two tokens?

**Comment by jackton1** [comment]
This issues was resolved by using the correct token. Thanks.
