### ISSUE TITLE
support Python formatter OITNB

### ISSUE THREAD

**Issue by zacharyburnettNOAA** [wearerequired/lint-action#241]
OITNB is a derivative of Black with more flexibility / options, and prefers single-quoted strings.

https://pypi.org/project/oitnb/

Would supporting this be as simple as adding lines to `action.yml` and a file to `src/linters`?

**Comment by ocean90** [comment]
Hey there, the steps to add a new linter are documented [here](https://github.com/wearerequired/lint-action/blob/master/CONTRIBUTING.md#adding-a-new-linter).

**Comment by zacharyburnettNOAA** [comment]
> Hey there, the steps to add a new linter are documented [here](https://github.com/wearerequired/lint-action/blob/master/CONTRIBUTING.md#adding-a-new-linter).

Oh wow, I'm dumb. Thanks, I will follow these steps!
