### ISSUE TITLE
Stylelint fails when there are no css files in the repo

### ISSUE THREAD

**Issue by paulsmithkc** [wearerequired/lint-action#265]
### Summary 

Sylelint fails when there are no css files in the repo. 

The error message is displayed as follows in the summary:

![image](https://user-images.githubusercontent.com/6501079/124311624-a69c2c80-db33-11eb-853c-c92252af5128.png)

However, the full output of the run displays the actual error message:

![image](https://user-images.githubusercontent.com/6501079/124311537-89675e00-db33-11eb-950e-3bf0ff73f249.png)

### Expected Behavior

No errors are displayed for stylelint, when there are no files to check.

**Comment by ocean90** [comment]
Hello there, if you don't want to have this as an error you have to set the `--allow-empty-input` argument:

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          stylelint: true
          stylelint_args: "--allow-empty-input"

See https://stylelint.io/user-guide/usage/cli/#--allow-empty-input---aei for information.

**Comment by paulsmithkc** [comment]
Thank you, that removes the error. Shouldn't the error that `lint-action` reports be the message below though?

`"Error: No files matching the pattern "**/*.{css,sass,scss}" were found."`
