### ISSUE TITLE
Differents results on github actions and vs code

### ISSUE THREAD

**Issue by antoniocra04** [wearerequired/lint-action#270]
I have script `"lint:prettier": "prettier --check --ignore-unknown \"**/*.*\"",`. Then I run it, I get successful result but in github actions I getting erorrs

Github action lint-action workflow: 
```
- name: Run linters
  uses: wearerequired/lint-action@v1
  with:
    prettier: true
```

![image](https://user-images.githubusercontent.com/40686374/125567844-ee0611b2-b9b5-4f26-a093-c910e426ea4d.png)
![image](https://user-images.githubusercontent.com/40686374/125567930-d03b4fab-9b3b-4631-beca-fcd4018e6b07.png)

.prettierrc.js:
```
module.exports = {
  semi: true,
  trailingComma: 'all',
  singleQuote: true,
  printWidth: 120,
  tabWidth: 2,
  endOfLine: 'auto',
};
```

.eslintrc.js:
```
module.exports = {
  parser: '@typescript-eslint/parser', // Specifies the ESLint parser
  extends: [
    'plugin:react/recommended', // Uses the recommended rules from @eslint-plugin-react
    'plugin:@typescript-eslint/recommended', // Uses the recommended rules from the @typescript-eslint/eslint-plugin
    'plugin:prettier/recommended', // Enables eslint-plugin-prettier and displays prettier errors as ESLint errors. Make sure this is always the last configuration in the extends array.
  ],
  parserOptions: {
    ecmaVersion: 2018, // Allows for the parsing of modern ECMAScript features
    sourceType: 'module', // Allows for the use of imports
    ecmaFeatures: {
      jsx: true, // Allows for the parsing of JSX
    },
  },
  rules: {
    'react/prop-types': [2, { ignore: ['children'] }],
  },
  settings: {
    react: {
      version: 'detect', // Tells eslint-plugin-react to automatically detect the version of React to use
    },
  },
};

```

**Comment by ocean90** [comment]
Hey there, thanks for the report but I'm not sure how to help you there. What you can try is enabling the `auto_fix` option and then inspect the changes to identify what the issues are.

PS: The `--ignore-unknown` argument  isn't one of the default arguments so you may have to add it via the `prettier_arg` option.

**Comment by antoniocra04** [comment]
Then I tried to enable auto_fix, and i getting fixes that not match with some rules. `prettier_args` not helping.
