### ISSUE TITLE
Can we only lint modified files?

### ISSUE THREAD

**Issue by Axedyson** [wearerequired/lint-action#292]
Did some research regarding #1 and found a GitHub action that helps with annotation via a `.json` file: https://github.com/Attest/annotations-action. 

They just released a new version of runner that helps with composite actions https://docs.github.com/en/actions/creating-actions/about-actions#composite-run-steps-actions

But it's not fully ready to support calling an action within another action yet (which I think is the main reason we need the composite action though lol https://github.com/actions/runner/issues/646#issuecomment-683160895

Here are the next steps for composite actions: https://github.com/actions/runner/issues/646

When expected action within action is released, we can leverage 
* file changes(conditional step, if to check for modified files or entire branch) https://github.com/trilom/file-changes-action 
* Run eslint and parse errors/warnings messages to follow https://github.com/Attest/annotations-action/blob/master/annotations.json (type definition: https://github.com/Attest/annotations-action/blob/master/src/annotation.ts)

_Originally posted by @theoomoregbee in https://github.com/wearerequired/lint-action/issues/47#issuecomment-687804620_

Is this issue still relevant today? Are we still waiting for github to release the functionality that enables us to lint only modified files?

**Comment by litso** [comment]
Would still love this feature
