### ISSUE TITLE
New Linter: isort

### ISSUE THREAD

**Issue by Joel-Giant** [wearerequired/lint-action#356]
My use case calls for black and isort in a Github workflow, it won't cause conflicts with black if the `--profile black` flag is passed, which can be added easily enough if a user wanted to run black with isort. I'm working through a PR, any immediate thoughts on adding isort as a formatter?

**Comment by ocean90** [comment]
Project page: https://pypi.org/project/isort/

I'm fine with adding for isort to the action.

Take a look at https://github.com/wearerequired/lint-action/blob/master/CONTRIBUTING.md#adding-a-new-linter to see what's needed to get a new linter/formatter added. Thanks!

**Comment by codeman1o1** [comment]
Is this still in progress?
If not, I would like to try to implement it

**Comment by Joel-Giant** [comment]
It's taken a backseat in my priorities unfortunately, but if you're willing to take it on by all means!
