### ISSUE TITLE
Remove unchanged files with check annotations [beta]

### ISSUE THREAD

**Issue by risoms** [wearerequired/lint-action#389]
Just curious if the `unchanged files with check annotations` inclusion is being introduced by this GitHub action or is widespread. If the later, Is there a way to specify linting only take place on edited files within a PR?

**Comment by ocean90** [comment]
Hello there, this message comes from GitHub but only exists because some of your files have linting issues. You should probably fix all the linting issues first and use this action to not introduce new issues.

It's currently not possible to only lint modified files, see #47.
