### ISSUE TITLE
Required test get overwritten after autofix

### ISSUE THREAD

**Issue by JanMedocs** [wearerequired/lint-action#390]
Hi,
If I turn on auto-fix lint-action push all fixes. Git requires some other tests that don't get fired after that fix.
If it is turned off it works pretty well.

After auto-fix:
![image](https://user-images.githubusercontent.com/61686304/152537480-c229737d-5f19-49b9-9e1e-a04e0edb1aab.png)

Without enabled auto-fix:
![Screenshot 2022-02-04 141124](https://user-images.githubusercontent.com/61686304/152537543-ec9cf0b0-9f34-47a8-bbec-41f52a668d3a.png)

Angular build and test/build (12.x) is the required test that needs to get fired each run if the pull is ready for review.

Greetings Jan

**Comment by ocean90** [comment]
Hello there, a push event by the default GitHub Action token does not trigger another workflow. You either have to use a personal access token as `github_token` input or you may want to try another event to trigger the other workflows.
