### ISSUE TITLE
Custom repository path

### ISSUE THREAD

**Issue by tcldr** [wearerequired/lint-action#42]
When creating a github workflow, it is sometimes useful to clone the repository (or multiple repositories) a level or two down from the default. e.g. to build and install a linter.

It would be useful to have a `repo-dir' option (defaulting to '.') from within which lint-action would run.

**Comment by samuelmeuli** [comment]
There's a [`[linter]_dir` option](https://github.com/samuelmeuli/lint-action#linter-specific-options) – does this help with what you're trying to achieve?

**Comment by tcldr** [comment]
No, unfortunately not.

As far as I can tell, the `[linter]_dir` option, will only focus the *linter* on a specific directory, but lint-action itself is still running at the workspace root level. Therefore, when lint-action runs its completion routine (getting the head ref, committing any auto-fix changes, etc.) it still expects to find a git repo at the top level of the workspace regardless of whether or not the `[linter]_dir`has been set.

This would probably be workable if more actions allowed working in the home dir, that way there would be a clear separation between the workspace being reserved for the current repo, and home for any supporting files/assets required for the current run – but unfortunately, the 'cache' action, and I assume many others only work within the workspace directory, whilst the 'checkout' action only supports specifying a path within the workspace directory.

Therefore, I can only assume that if we need assets beyond the contents of the current repo, github intends for us to create a sub-dir for within the workspace dir and checkout to that instead.

**Comment by samuelmeuli** [comment]
> the workspace being reserved for the current repo

That's how I understand the docs. From [here](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables):

> `GITHUB_WORKSPACE`: The GitHub workspace directory path. The workspace directory contains a subdirectory with a copy of your repository if your workflow uses the `actions/checkout` action. If you don't use the `actions/checkout` action, the directory will be empty. For example, `/home/runner/work/my-repo-name/my-repo-name`.

Maybe you could store the other files in a directory adjacent to the repo, e.g. `/home/runner/work/my-repo-name/assets`? [The cache action seems to support non-workspace directories.](https://github.com/actions/cache/issues/229#issuecomment-603480748)

**Comment by tcldr** [comment]
Ahh, so the cache docs are incorrect. That’s good to know. I’ll try that.
