### ISSUE TITLE
Warning: Unexpected input(s) 'autopep8_auto_fix'

### ISSUE THREAD

**Issue by codeman1o1** [wearerequired/lint-action#478]
Like the title says, there is no `autopep8_auto_fix` option

**Comment by ocean90** [comment]
You're right, it's missing in https://github.com/wearerequired/lint-action/blob/220c8782e495b4baf1374931227bb666a71b9ab0/action.yml#L225-L243.

**Comment by codeman1o1** [comment]
Wrong repo ^^^
