### ISSUE TITLE
New Linter: Markdownlint

### ISSUE THREAD

**Issue by chiefpansancolt** [wearerequired/lint-action#481]
Would be great to add support for markdownlint https://github.com/DavidAnson/markdownlint, I use this on a number of projects and 100% of projects have at least 1-3 .md files in them.

**Comment by ocean90** [comment]
Sounds good. If anyone wants to submit a PR, [here](https://github.com/wearerequired/lint-action/blob/master/CONTRIBUTING.md#adding-a-new-linter) are the necessary steps documented.
