### ISSUE TITLE
Use job summaries instead of reporting actions through the API?

### ISSUE THREAD

**Issue by CraigSiemens** [wearerequired/lint-action#499]
It's been reported multiple times that the actions are being shown under the wrong workflow in GitHub, but that it's an issue with the API that this action cant fix. #401, #280, #97, #93

As a potential workaround for the issue, would it be possible to report Job Summaries, either as an option or a replacement for reporting the status?

https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

It's mentioned as a workaround in this community discussion.

https://github.community/t/github-actions-status-checks-created-on-incorrect-check-suite-id/16685

**Comment by ocean90** [comment]
Hey there, job summaries are not really a replacement for the Checks API as they don't provide inline annotations or can be used for branch protections.

I'm not sure if there's any benefit in having job summaries for lint results. But maybe I'm missing something?

**Comment by CraigSiemens** [comment]
I don't think it specifically has a benefit other than moving away from using the Checks API. It's been buggy for a couple years at this point and doesn't seem like it's going to be fixed any time soon

[Workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions) could be another option for adding annotations to lines of code. The only difference I see with this one is the annotations would be under show workflow that called this action instead of a separate check for each lint tool.
