### ISSUE TITLE
ClangFormat isn't supported anymore ?

### ISSUE THREAD

**Issue by cmnemoi** [wearerequired/lint-action#549]
Hello, I am trying to use this action with clang-format and I get the following warning : 

`Warning: Unexpected input(s) 'clang_format', 'clang_format_args', 'clang_format_auto_fix', 'clang_format_dir', valid inputs are ['github_token', 'continue_on_error', 'auto_fix', 'commit', 'git_no_verify', 'git_name', 'git_email', 'commit_message', 'check_name', 'neutral_check_on_warning', 'stylelint', 'stylelint_args', 'stylelint_dir', 'stylelint_extensions', 'stylelint_command_prefix', 'stylelint_auto_fix', 'gofmt', 'gofmt_args', 'gofmt_dir', 'gofmt_extensions', 'gofmt_command_prefix', 'gofmt_auto_fix', 'golint', 'golint_args', 'golint_dir', 'golint_extensions', 'golint_command_prefix', 'golint_auto_fix', 'eslint', 'eslint_args', 'eslint_dir', 'eslint_extensions', 'eslint_command_prefix', 'eslint_auto_fix', 'prettier', 'prettier_args', 'prettier_dir', 'prettier_extensions', 'prettier_command_prefix', 'prettier_auto_fix', 'xo', 'xo_args', 'xo_dir', 'xo_extensions', 'xo_command_prefix', 'xo_auto_fix', 'php_codesniffer', 'php_codesniffer_args', 'php_codesniffer_dir', 'php_codesniffer_extensions', 'php_codesniffer_command_prefix', 'php_codesniffer_auto_fix', 'autopep8', 'autopep8_args', 'autopep8_dir', 'autopep8_extensions', 'autopep8_command_prefix', 'autopep8_auto_fix', 'black', 'black_args', 'black_dir', 'black_extensions', 'black_command_prefix', 'black_auto_fix', 'flake8', 'flake8_args', 'flake8_dir', 'flake8_extensions', 'flake8_command_prefix', 'flake8_auto_fix', 'mypy', 'mypy_args', 'mypy_dir', 'mypy_extensions', 'mypy_command_prefix', 'mypy_auto_fix', 'oitnb', 'oitnb_args', 'oitnb_dir', 'oitnb_extensions', 'oitnb_command_prefix', 'oitnb_auto_fix', 'pylint', 'pylint_args', 'pylint_dir', 'pylint_extensions', 'pylint_command_prefix', 'pylint_auto_fix', 'rubocop', 'rubocop_args', 'rubocop_dir', 'rubocop_extensions', 'rubocop_command_prefix', 'rubocop_auto_fix', 'erblint', 'erblint_args', 'erblint_dir', 'erblint_extensions', 'erblint_command_prefix', 'erblint_auto_fix', 'swiftformat', 'swiftformat_args', 'swiftformat_dir', 'swiftformat_extensions', 'swiftformat_command_prefix', 'swiftformat_auto_fix', 'swift_format_lockwood', 'swift_format_lockwood_args', 'swift_format_lockwood_dir', 'swift_format_lockwood_extensions', 'swift_format_lockwood_command_prefix', 'swift_format_lockwood_auto_fix', 'swift_format_official', 'swift_format_official_args', 'swift_format_official_dir', 'swift_format_official_extensions', 'swift_format_official_command_prefix', 'swift_format_official_auto_fix', 'swiftlint', 'swiftlint_args', 'swiftlint_dir', 'swiftlint_extensions', 'swiftlint_command_prefix', 'swiftlint_auto_fix', 'dotnet_format', 'dotnet_format_args', 'dotnet_format_dir', 'dotnet_format_extensions', 'dotnet_format_command_prefix', 'dotnet_format_auto_fix']`

Is ClangFormat still supported or is it a bug?

**Comment by ocean90** [comment]
A version with `clang_format` support is not released yet. If you want to give it a try you can use `wearerequired/lint-action@640cbd3acbeb113f05067c41db28f1836e1861ce`.
