### ISSUE TITLE
auto_fix with verified commits failing

### ISSUE THREAD

**Issue by cj** [wearerequired/lint-action#592]
Currently auto fix fails if you have the option "Require signed commits", as lint-action does not commit with a verified signature:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/1819/215139780-98379ae0-4794-4622-9083-01f80d9cd0dc.png">

It is possible to commit verified commits using the API https://github.blog/2019-08-15-commit-signing-support-for-bots-and-other-github-apps / https://github.com/swinton/commit

**Comment by ocean90** [comment]
See https://github.com/wearerequired/lint-action/issues/259#issuecomment-861510720 for how to enable signed commits.
