### ISSUE TITLE
Example how to prevent release

### ISSUE THREAD

**Issue by ozum** [wearerequired/lint-action#60]
Hi,

Related to #31 and #50. I understand not failing main job is by design of this action. However, I could not figure out how to prevent next release step if there are lint errors.

Could you provide a basic example how to prevent next step if there are lint errors?

Thanks,

**Comment by markphip** [comment]
I do not understand how/why those other issues were closed without addressing the root issue/questions being asked. It is fine if the current behavior is what is desired but it seems like there ought to at least be some documentation on how to detect and handle errors produced by lint? If black reformats my code and pushes a new commit, why would I want to continue my action and do a build and deploy .. as one example.

It seems like an easy compromise would be for the action to add one our more outputs that could then be checked in downstream steps if we wanted to end the job or skip something. It could just be a single boolean that says if any of the lints failed, or you could provide one output for each lint if that is preferred.

**Comment by jnm2** [comment]
This was quite surprising to me too. Most other linter GitHub actions that I've used fail the job, and that's the only behavior I'd want.
