### ISSUE TITLE
Can you get this action verified?

### ISSUE THREAD

**Issue by markphip** [wearerequired/lint-action#607]
I note that your organization is verified but you are not a verified creator in the Marketplace for your actions. There is an organization setting to allow verified actions. If this is used then all unverified actions must be added to an allowed actions list.

It would be nice if this action was verified.

https://docs.github.com/en/apps/publishing-apps-to-github-marketplace/github-marketplace-overview/about-marketplace-badges#for-github-actions

**Comment by ocean90** [comment]
Hello there, we're not a partner organization of GitHub.
