### ISSUE TITLE
Rejected Remote Issue

### ISSUE THREAD

**Issue by AlexMachin1997** [wearerequired/lint-action#65]
Hi,

I've been using lint-action for a while now and most of the time it's been fine, however, I've noticed after creating a new "feature" and my linitng task is failing. I get the following output:

![image](https://user-images.githubusercontent.com/29917195/86533046-480f8480-bec6-11ea-9ddc-43996fa41c8e.png)

Im not entirely sure what I can do to solve this issue, is there a way to get a new github token for the current branch or is this related to the token scoping Github has put in place ?

I really want to add this to our Github flow at work, I've used in all my personal projects and I love it, but I keep getting errors like this and I don't understand them fully or how to fix them.

Any help would greatly be appreciated 👍 

Project Link: https://github.com/AlexMachin1997/TheOpenMovieDB-React-Example/actions

**Comment by ocean90** [comment]
Sounds like the same issue mentioned in https://github.com/samuelmeuli/lint-action/issues/74. The linter seems to change the workflow file and committing the change isn't allowed for the default GitHub token. A fix would be to ensure that the file has the correct style by running the linter and committing the changes locally.

**Comment by AlexMachin1997** [comment]
Yeah that's my post aswell lol.

I basically spoke to some people on Githubs new forum system and yeah the eslint tries to modify the workflow files, it makes sense it does this as it's trying to fix an issue with the code. However, in this particular instance we don't need it to, there has got to be a away to have an internal eslintignore.

For now anyone else having this issue should just tell eslint to ignore .github directory.
