### ISSUE TITLE
ESlint config changes will change --ext usage

### ISSUE THREAD

**Issue by j-fulbright** [wearerequired/lint-action#739]
An option to remove the passing of the --ext option for ESlint would be appreciated. 

V9 of Eslint will be moving to flat configs with glob patterns which no longer will work correctly with --ext, An option to disable that would be useful

**Comment by JohnCampionJr** [comment]
Thank you; my issue got marked stale :(
https://github.com/wearerequired/lint-action/issues/730

**Comment by JohnCampionJr** [comment]
This is the problem with auto-marking things as stale.  This is an open issue.
