### ISSUE TITLE
Support for Node 20

### ISSUE THREAD

**Issue by svandragt** [wearerequired/lint-action#810]
>The following actions uses Node.js version which is deprecated and will be forced to run on node20: ..., wearerequired/lint-action@v2. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

It seems to run fine, but it would be good to officially support it?

**Comment by ocean90** [comment]
Duplicate of #787.
