### ISSUE TITLE
linter tool jobs get added to random workflows

### ISSUE THREAD

**Issue by moodysalem** [wearerequired/lint-action#97]
Why do they get added to random workflows instead of the workflow they are in?

It's super weird

e.g.
https://github.com/Uniswap/uniswap-lib/actions/runs/315950774

This action does static analysis, but randomly contains a prettier job

**Comment by ocean90** [comment]
Hi there, this is an issue with how the GitHub checks API works. Checks are attached to commit SHAs and the annotations are added to latest workflow run for the commit being tested.

Related report: https://github.community/t/github-actions-status-checks-created-on-incorrect-check-suite-id/16685
